### PR TITLE
publish to PyPI

### PR DESCRIPTION
**Pull request by ocefpaf**
@sckott can you grant @7yl4r and myself PyPI maintainer status for this package? This PR will automate the releases based on GH actions but we need set set the token and be able to yank releases if necessary.

@7yl4r We can merge this one but we can only issue releases after we add the token to this repo.

### CODE REVIEW

**Comment by 7yl4r** [comment]
@ocefpaf : what should we do if we don't hear from @sckott

**Comment by ocefpaf** [comment]
> @ocefpaf : what should we do if we don't hear from @sckott

Ideally we should keep the project here. If we don't hear from him we can move it to the IOOS org where we would have the right permissions. But I'd like to avoid that if we can.

**Comment by sckott** [comment]
working on it

**Comment by sckott** [comment]
@ocefpaf you should be getting an invitation email from pypi. 

@7yl4r what's your pypi username?

**Comment by 7yl4r** [comment]
It's 7yl4r. I just set it up.  Thanks!

**Comment by sckott** [comment]
invitiatoin sent

**Comment by ocefpaf** [comment]
Thanks @sckott!

**Comment by ocefpaf** [comment]
@7yl4r this PR is ready to go. The last step is to add the PyPI token to this repository secrets. We will need someone with elevated rights here to do so. Maybe @pieterprovoost can help us out?

**Comment by pieterprovoost** [comment]
@ocefpaf @7yl4r Added `PYPI_API_TOKEN`, can you please check?

**Comment by pieterprovoost** [comment]
Sorry about that, I have bumped your privileges.

**Comment by 7yl4r** [comment]
I see the secret; looks good. I just created a release, but it appears the github action did not trigger. Should we be using `on:release` [[ref](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release)] instead of using [`if: ${{github.event_name == 'release'}}`](https://github.com/iobis/pyobis/blob/39204d5c470b7e3399becbfefc9468d271b3f569/.github/workflows/pypi.yml#L41)?

**Comment by ocefpaf** [comment]
That if-clause works on my  projects but is is worth testing on release only. I use it that way b/c we run on PRs are a tarball test and then on release to publish.

**Pull request merged**
