### PR TITLE
[Fix] Created dataset module and other module changes.

### PR DESCRIPTION
**Pull request by ayushanand18**
# Overview of changes
+ I have changed the pyobis/nodes, occurrences, checklist, and taxa modules to integrate them with OBIS v3 API and updated README with new example usage for the modules.
+ I have also created a new dataset module to connect to the obis/dataset endpoint. 
+ I have also deleted pyobis/groups and pyobis/resources because they have become obsolete.
(Refer: [https://github.com/iobis/pyobis/pull/8#issuecomment-1084317926](https://github.com/iobis/pyobis/pull/8#issuecomment-1084317926) )

# Notes for reviewers
You can run tests on your local machine whether the above 5 modules are working as expected.

# Questions for reviewers
No questions for reviewers.

### CODE REVIEW

**Comment by ayushanand18** [comment]
@pieterprovoost @ocefpaf I'm sorry for pinging you here, but just wanted to request feedback on this PR. 

I know you'd have been very busy since a couple of weeks due to the GSoC timeline. May I ask for the code review, I have removed the `resources` module plus also included a new module for `dataset` endpoint. I have also updated the README with the new syntax and nomenclature. 

Additionally, all tests in this branch have failed but I have worked on them and we will need one more patch to fix them (you can see the workflow run on my fork, https://github.com/ayushanand18/pyobis/actions/runs/2184556665 Status: [Tests](https://github.com/ayushanand18/pyobis/actions/workflows/tests.yml) ).

Your feedback will help me improve this PR. Thanks in advance! :)

**Comment by ocefpaf** [comment]
@ayushanand18 most of the GSoC mentors are in the IOOS Code Sprint this week and we are quite busy.
Also, I already touched base with you on this but if you can send smaller PRs with a single context it would help us a lot to review and merge. This PR removed a lot of files, changed config stuff, and added tests. Those should all be in separated PRs.

**Comment by ayushanand18** [comment]
Thanks a ton @ocefpaf for the review. I am sorry for adding so many changes to a single PR. \
I'll focus on smaller and more easy to review PRs in future. Thanks again for your review and once again very sorry to disturb amidst a tight schedule.

Thank you so much @pieterprovoost :)

**Comment by ocefpaf** [comment]
> I am sorry for adding so many changes to a single PR.

Don't be. There is nothing wrong. This is about how communities/people work and that usually takes time and iteration. Just be patient with us and we'll fine tune the PRs to take the most of your contributions.

**Comment by ayushanand18** [comment]
Thank you so much @ocefpaf :) I have learned so much from the Open Source community and especially during my time spent understanding the pyobis project. I have so much to learn more about, and I am excited about the future!

**Pull request merged**
