### PR TITLE
Fix. Tests and MoF improved accessibility

### PR DESCRIPTION
**Pull request by ayushanand18**
# Overview of changes
With this PR, we have got two major objectives accomplished:
+ the tests are passing again
+ the MoF response from occurrences.search() function now returns as a list of pandas dataframes.

# Notes for reviewers
I'm sorry for this huge PR, but the initial work like getting all modules to work, writing and making all tests work was I guess the first priority before accomplishing the primary objectives for this summer.

# Next Steps
I am now working on dropping the obisDownloads, and on update-specific branches.

### CODE REVIEW

**Review by 7yl4r — APPROVED** [review]

**Comment by ayushanand18** [comment]
> The edits look good overall, but there is a lot here.
> 
> @ayushanand18 : can you resolve the merge conflicts noted below?

Thanks a ton @7yl4r, I am working on resolving the merge conflicts.

**Comment by ayushanand18** [comment]
> @ayushanand18 : can you resolve the merge conflicts noted below?

I have removed changes to those files. Maybe, we need one more PR get those changes back after this PR gets merged. 

The changes which I had to revert include,
+ removing the obsolete functions from taxa,
+ README updates for module usage examples,
+ the EXAMPLES usage for occurrence and other modules, 
+ and new functions from the occurrences included in the pyobis/__init__.py. 

However, this might make some tests to fail.

**Comment by 7yl4r** [comment]
Let's try to get PRs a bit cleaner in the future by making smaller PRs on feature branches, but I am going to go ahead and merge this one and whatever else we need to get things caught up with your dev environment.

**Comment by ayushanand18** [comment]
Thanks a ton @7yl4r! I will make sure I address only one objective for one PR for all subsequent PRs.

I am now working on making commits to revert back those changes I had to undo to resolve merge conflicts.

**Pull request merged**
