### PR TITLE
[Jupyter Notebooks] `migration_patterns.ipynb` a geo-temporal analysis

### PR DESCRIPTION
**Pull request by ayushanand18**
## Overview
This notebook analysis spatial migrations for species through three methods:
+ Plotting an year-wise world map so that a user can personally view the year wise records
+ Creating a GIF of maps to interactively show the changes in locations
+ A 3D latitude, longitude time series plot to track location changes

There is an initial implementation for *Mola mola*. Subsequently I have created a class and defined methods to grab data, plot an interactive plot and create a gif for any species. This makes analysis easy for any species.

## Notes for reviewers
Please review the data and analysis in this notebook. I have dropped some records that were having unexpected `eventDate` values as in #45.

## Next Steps
I am now working on the docs.

Thank you!

### CODE REVIEW

**Comment by 7yl4r** [comment]
This `.ipynb` file is currently not parsing as valid JSON. I tried opening in GitHub, Colab, and ReviewNB; all fail with the same error.

**Comment by ayushanand18** [comment]
I will try to push this notebook again maybe there was a glitch while uploading to GitHub from colab.

**Comment by 7yl4r** [comment]
This notebook lays groundwork for some powerful visualization techniques, but it also introduces significant code complexity and dependencies.

Before merging it I think we should have a discussion about #20. I think we ought to put the heavier analysis & visualization components into another package. This would ensure pyobis stays light & easy to maintain while also allowing us to create DRY code for OBIS analyses.

**Comment by ayushanand18** [comment]
> This notebook lays groundwork for some powerful visualization techniques, but it also introduces significant code complexity and dependencies.

This is true, for a researcher who doesn't have to do with these python libraries and maybe say ingests this data through python into a processing pipeline won't ever need these heavy dependencies.

> Before merging it I think we should have a discussion about #20. I think we ought to put the heavier analysis & visualization components into another package. This would ensure pyobis stays light & easy to maintain while also allowing us to create DRY code for OBIS analyses.

I would agree with this. The previous two analysis notebooks were a lot simpler and easy to catch than this analysis. We might ship this notebook into an entirely different repo which focuses entirely on bringing OBIS data to use through pyobis.

**Comment by ayushanand18** [comment]
> This code is too complicated for a researcher-facing notebook. The vast majority of researchers don't know what a _class_ is.

I totally agree with this. but my main aim of creating a *class* was to make it super easy for them to create interactive plots and GIFs for any species. In this notebook I demonstrated the process of analysis through *Mola mola* like a story, and then went on to create a class to ease this process for other species. I tried removing the redundancy with the *class*. Maybe we can reuse this class in #20 or let a researcher generate these plots with minimal efforts. Did it sound right? If not, what other approach should I come up with?

**Comment by ayushanand18** [comment]
> 1. It is hard to visualize which direction the "map" would be oriented. I can tell which axes are lat/lon and that the map plane is perpendicular to the time axis, but it takes some mental work. Maybe a basemap on the back wall would help? I expect that making that happen would be more work than it is worth.
Noted. I'll try to add a plot on the back and figure out if it looks right.

> 2. The overlapping points make it hard to differentiate axes. I suggest we add a colormap to one of the axes. Maybe `year` since it is the odd man out amongst the two spatial variables.
That's a good idea to add colormap to the year parameter. I'll try to figure out if that's doable on 3D plot.

**Comment by ayushanand18** [comment]
> 1. It is hard to visualize which direction the "map" would be oriented. I can tell which axes are lat/lon and that the map plane is perpendicular to the time axis, but it takes some mental work. Maybe a basemap on the back wall would help? I expect that making that happen would be more work than it is worth.
> 2. The overlapping points make it hard to differentiate axes. I suggest we add a colormap to one of the axes. Maybe `year` since it is the odd man out amongst the two spatial variables.

Update: I have updated the 3D graph, and it looks like this. Does it look how we were hoping for?
image

**Comment by ayushanand18** [comment]
<p>This is a very nice idea to generate a meaningful analysis. But that is a lot trickier too. I tried using <code>matplotlib.animations</code>  but there's a catch. The animated doesn't show up in a Jupyter Notebook (and on Google Colab too but will run on JupyterLab environs like AWS Sagemaker etc) because of the display used by matplotlib. Default: matplotlib uses <code>headless</code> so animations are not shown. I couldn't find any other way to tackle this, could you please advise?</p>

---

 <a href='https://app.reviewnb.com/iobis/pyobis/pull/47/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MathewBiddle** [comment]
@ocefpaf how have we displayed these types of graphics in the Code Lab? Do we just use nbconvert to create the html pages and present those on the website? Or is there a 'trick' with Jupyter notebooks?

**Comment by 7yl4r** [comment]
> > 1. It is hard to visualize which direction the "map" would be oriented. I can tell which axes are lat/lon and that the map plane is perpendicular to the time axis, but it takes some mental work. Maybe a basemap on the back wall would help? I expect that making that happen would be more work than it is worth.
> > 2. The overlapping points make it hard to differentiate axes. I suggest we add a colormap to one of the axes. Maybe `year` since it is the odd man out amongst the two spatial variables.
> 
> Update: I have updated the 3D graph, and it looks like this. Does it look how we were hoping for? image

Oh that's cool. Well done! We might play with different colormaps, but I am happy with this.

**Comment by ayushanand18** [comment]
> Oh that's cool. Well done! We might play with different colormaps, but I am happy with this.

Thank you so much! :)

**Comment by ocefpaf** [comment]
> @ocefpaf how have we displayed these types of graphics in the Code Lab? Do we just use nbconvert to create the html pages and present those on the website? Or is there a 'trick' with Jupyter notebooks?

No trick, under the hood the jupyter book is calling nbconvert. There a few cavetas for widgets and fancy plots that call JS libraries. For those we need to always click on the "Trust notebook" and save the widget state before committing.  (Remember the despairing maps? That is b/c I forget to save the widget state.)

**Pull request merged**
