### PR TITLE
Occurrences.search function update to bring in consistency in response

### PR DESCRIPTION
**Pull request by ayushanand18**
## Overview
This PR aims to bring in fixes that were discussed in #61. The final response of the search function is a `pandas dataframe`. 

## Changes introduced
Now all concatenation occurs on pandas dataframe. There are some interesting findings in #61. #82 is an interesting test and it should follow the former.

Thanks!

### CODE REVIEW

**Comment by 7yl4r** [comment]
@ayushanand18 : I think if you accept this PR: https://github.com/ayushanand18/pyobis/pull/2 then the test will be added here as well and we can see it pass before merging.

**Comment by ayushanand18** [comment]
> @ayushanand18 : I think if you accept this PR: [ayushanand18#2](https://github.com/ayushanand18/pyobis/pull/2) then the test will be added here as well and we can see it pass before merging.

Did that, and these tests are passing. Woo!

**Comment by ayushanand18** [comment]
I did a rebase and then pushed those changes.

**Comment by 7yl4r** [comment]
:tada: looks great!

**Pull request merged**
